In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50])

In [4]:
a

array([10, 20, 30, 40, 50])

In [5]:
i=np.where(a>25)

In [6]:
i

(array([2, 3, 4], dtype=int64),)

In [7]:
x=np.array([[1,2],[3,4],[5,6]])

# working on bank nifty

In [10]:
import pandas as pd
df1=pd.read_csv('nifty3jan.csv')

FileNotFoundError: [Errno 2] File b'nifty3jan.csv' does not exist: b'nifty3jan.csv'

In [ ]:
df1.head()

In [1]:
import os
os.chdir("C:\\Users\\bired\\Desktop\\pics")
df2=pd.read_csv("nifty.ce.csv")

NameError: name 'pd' is not defined

In [2]:
df2.iloc[2:]

NameError: name 'df2' is not defined

In [3]:
df_all = pd.concat([df1, df2])
df_all

NameError: name 'pd' is not defined

In [4]:
import os, sys

# Open a file
path = "C:\\Users\\bired\\Desktop\\pics\\project data"
dirs = os.listdir( path )

In [5]:
dirs

['jupyter.29-07-19.ipynb',
 'OPTIDX_BANKNIFTY_CE_02-May-2019_TO_09-May-2019 (1).csv',
 'OPTIDX_BANKNIFTY_CE_03-Jan-2019_TO_10-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_CE_04-Apr-2019_TO_11-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_CE_06-Jun-2019_TO_13-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_CE_07-Feb-2019_TO_14-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_CE_07-Mar-2019_TO_14-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_CE_09-May-2019_TO_16-May-2019.csv',
 'OPTIDX_BANKNIFTY_CE_10-Jan-2019_TO_17-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_CE_11-Apr-2019_TO_18-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_CE_13-Jun-2019_TO_20-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_CE_14-Feb-2019_TO_21-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_CE_14-Mar-2019_TO_21-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_CE_16-May-2019_TO_23-May-2019 (1).csv',
 'OPTIDX_BANKNIFTY_CE_17-Jan-2019_TO_24-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_CE_18-Apr-2019_TO_25-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_CE_21-Feb-2019_TO_28-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_CE_21-Mar-2019_TO_28-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_CE_23-May-2019_TO_30-May-2019.csv',
 'OPTIDX_BANKNIFTY_CE_24-Jan-2019_TO_31-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_CE_25-Apr-2019_TO_02-May-2019.csv',
 'OPTIDX_BANKNIFTY_CE_27-Dec-2018_TO_03-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_CE_28-Feb-2019_TO_07-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_CE_28-Mar-2019_TO_04-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_CE_30-May-2019_TO_06-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_CE_31-Jan-2019_TO_07-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_PE_02-May-2019_TO_09-May-2019.csv',
 'OPTIDX_BANKNIFTY_PE_03-Jan-2019_TO_10-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_PE_04-Apr-2019_TO_11-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_PE_06-Jun-2019_TO_13-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_PE_07-Feb-2019_TO_14-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_PE_07-Mar-2019_TO_14-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_PE_09-May-2019_TO_16-May-2019.csv',
 'OPTIDX_BANKNIFTY_PE_10-Jan-2019_TO_17-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_PE_11-Apr-2019_TO_18-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_PE_13-Jun-2019_TO_20-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_PE_14-Feb-2019_TO_21-Feb-2019 (1).csv',
 'OPTIDX_BANKNIFTY_PE_14-Mar-2019_TO_21-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_PE_16-May-2019_TO_23-May-2019.csv',
 'OPTIDX_BANKNIFTY_PE_17-Jan-2019_TO_24-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_PE_18-Apr-2019_TO_25-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_PE_21-Feb-2019_TO_28-Feb-2019.csv',
 'OPTIDX_BANKNIFTY_PE_21-Mar-2019_TO_28-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_PE_23-May-2019_TO_30-May-2019.csv',
 'OPTIDX_BANKNIFTY_PE_24-Jan-2019_TO_31-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_PE_25-Apr-2019_TO_02-May-2019 (1).csv',
 'OPTIDX_BANKNIFTY_PE_27-Dec-2018_TO_03-Jan-2019.csv',
 'OPTIDX_BANKNIFTY_PE_28-Feb-2019_TO_07-Mar-2019.csv',
 'OPTIDX_BANKNIFTY_PE_28-Mar-2019_TO_04-Apr-2019.csv',
 'OPTIDX_BANKNIFTY_PE_30-May-2019_TO_06-Jun-2019.csv',
 'OPTIDX_BANKNIFTY_PE_31-Jan-2019_TO_07-Feb-2019.csv']

In [61]:
import pandas as pd
df=pd.DataFrame(dirs)
df.head()
#print(df.columns)

                                                   0
0                             jupyter.29-07-19.ipynb
1  OPTIDX_BANKNIFTY_CE_02-May-2019_TO_09-May-2019...
2  OPTIDX_BANKNIFTY_CE_03-Jan-2019_TO_10-Jan-2019...
3  OPTIDX_BANKNIFTY_CE_04-Apr-2019_TO_11-Apr-2019...
4  OPTIDX_BANKNIFTY_CE_06-Jun-2019_TO_13-Jun-2019...

In [62]:
pwd()

'C:\\Users\\bired\\Desktop\\pics'

In [63]:
import os
os.chdir("C:\\Users\\bired\\Desktop\\pics\\project data")

In [64]:
df.shape

(51, 1)

In [65]:
# This would print all the files and directories
for file in dirs:
    print(file)

jupyter.29-07-19.ipynb
OPTIDX_BANKNIFTY_CE_02-May-2019_TO_09-May-2019 (1).csv
OPTIDX_BANKNIFTY_CE_03-Jan-2019_TO_10-Jan-2019.csv
OPTIDX_BANKNIFTY_CE_04-Apr-2019_TO_11-Apr-2019.csv
OPTIDX_BANKNIFTY_CE_06-Jun-2019_TO_13-Jun-2019.csv
OPTIDX_BANKNIFTY_CE_07-Feb-2019_TO_14-Feb-2019.csv
OPTIDX_BANKNIFTY_CE_07-Mar-2019_TO_14-Mar-2019.csv
OPTIDX_BANKNIFTY_CE_09-May-2019_TO_16-May-2019.csv
OPTIDX_BANKNIFTY_CE_10-Jan-2019_TO_17-Jan-2019.csv
OPTIDX_BANKNIFTY_CE_11-Apr-2019_TO_18-Apr-2019.csv
OPTIDX_BANKNIFTY_CE_13-Jun-2019_TO_20-Jun-2019.csv
OPTIDX_BANKNIFTY_CE_14-Feb-2019_TO_21-Feb-2019.csv
OPTIDX_BANKNIFTY_CE_14-Mar-2019_TO_21-Mar-2019.csv
OPTIDX_BANKNIFTY_CE_16-May-2019_TO_23-May-2019 (1).csv
OPTIDX_BANKNIFTY_CE_17-Jan-2019_TO_24-Jan-2019.csv
OPTIDX_BANKNIFTY_CE_18-Apr-2019_TO_25-Apr-2019.csv
OPTIDX_BANKNIFTY_CE_21-Feb-2019_TO_28-Feb-2019.csv
OPTIDX_BANKNIFTY_CE_21-Mar-2019_TO_28-Mar-2019.csv
OPTIDX_BANKNIFTY_CE_23-May-2019_TO_30-May-2019.csv
OPTIDX_BANKNIFTY_CE_24-Jan-2019_TO_31-Jan-2019.csv
OPTIDX_BANKNIFTY_CE_25-Apr-2019_TO_02-May-2019.csv
OPTIDX_BANKNIFTY_CE_27-Dec-2018_TO_03-Jan-2019.csv
OPTIDX_BANKNIFTY_CE_28-Feb-2019_TO_07-Mar-2019.csv
OPTIDX_BANKNIFTY_CE_28-Mar-2019_TO_04-Apr-2019.csv
OPTIDX_BANKNIFTY_CE_30-May-2019_TO_06-Jun-2019.csv
OPTIDX_BANKNIFTY_CE_31-Jan-2019_TO_07-Feb-2019.csv
OPTIDX_BANKNIFTY_PE_02-May-2019_TO_09-May-2019.csv
OPTIDX_BANKNIFTY_PE_03-Jan-2019_TO_10-Jan-2019.csv
OPTIDX_BANKNIFTY_PE_04-Apr-2019_TO_11-Apr-2019.csv
OPTIDX_BANKNIFTY_PE_06-Jun-2019_TO_13-Jun-2019.csv
OPTIDX_BANKNIFTY_PE_07-Feb-2019_TO_14-Feb-2019.csv
OPTIDX_BANKNIFTY_PE_07-Mar-2019_TO_14-Mar-2019.csv
OPTIDX_BANKNIFTY_PE_09-May-2019_TO_16-May-2019.csv
OPTIDX_BANKNIFTY_PE_10-Jan-2019_TO_17-Jan-2019.csv
OPTIDX_BANKNIFTY_PE_11-Apr-2019_TO_18-Apr-2019.csv
OPTIDX_BANKNIFTY_PE_13-Jun-2019_TO_20-Jun-2019.csv
OPTIDX_BANKNIFTY_PE_14-Feb-2019_TO_21-Feb-2019 (1).csv
OPTIDX_BANKNIFTY_PE_14-Mar-2019_TO_21-Mar-2019.csv
OPTIDX_BANKNIFTY_PE_16-May-2019_TO_23-May-2019.csv
OPTIDX_BANKNIFTY_PE_17-Jan-2019_TO_24-Jan-2019.csv
OPTIDX_BANKNIFTY_PE_18-Apr-2019_TO_25-Apr-2019.csv
OPTIDX_BANKNIFTY_PE_21-Feb-2019_TO_28-Feb-2019.csv
OPTIDX_BANKNIFTY_PE_21-Mar-2019_TO_28-Mar-2019.csv
OPTIDX_BANKNIFTY_PE_23-May-2019_TO_30-May-2019.csv
OPTIDX_BANKNIFTY_PE_24-Jan-2019_TO_31-Jan-2019.csv
OPTIDX_BANKNIFTY_PE_25-Apr-2019_TO_02-May-2019 (1).csv
OPTIDX_BANKNIFTY_PE_27-Dec-2018_TO_03-Jan-2019.csv
OPTIDX_BANKNIFTY_PE_28-Feb-2019_TO_07-Mar-2019.csv
OPTIDX_BANKNIFTY_PE_28-Mar-2019_TO_04-Apr-2019.csv
OPTIDX_BANKNIFTY_PE_30-May-2019_TO_06-Jun-2019.csv
OPTIDX_BANKNIFTY_PE_31-Jan-2019_TO_07-Feb-2019.csv

In [77]:
import glob, os    
df = pd.concat(map(pd.read_csv, glob.glob(os.path.join('C:\\Users\\bired\\Desktop\\pics\\project data', "*.csv"))))

In [78]:
df

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value
0,BANKNIFTY,02-May-2019,09-May-2019,CE,26200,0.00,0.00,0.00,2009.40,0.00,3542.85,0,0.00,0.00,0,0,-
1,BANKNIFTY,02-May-2019,09-May-2019,CE,32100,0.00,0.00,0.00,83.80,0.00,0.40,0,0.00,0.00,0,0,-
2,BANKNIFTY,02-May-2019,09-May-2019,CE,26400,0.00,0.00,0.00,1841.30,0.00,3343.15,0,0.00,0.00,0,0,-
3,BANKNIFTY,02-May-2019,09-May-2019,CE,26500,0.00,0.00,0.00,1759.45,0.00,3243.25,0,0.00,0.00,0,0,-
4,BANKNIFTY,02-May-2019,09-May-2019,CE,26600,0.00,0.00,0.00,1679.10,0.00,3143.40,0,0.00,0.00,0,0,-
5,BANKNIFTY,02-May-2019,09-May-2019,CE,26700,3100.00,3100.00,3077.80,3077.80,3077.80,3077.80,2,11.92,1.24,40,40,-
6,BANKNIFTY,02-May-2019,09-May-2019,CE,26800,0.00,0.00,0.00,1523.40,0.00,2943.65,0,0.00,0.00,0,0,-
7,BANKNIFTY,02-May-2019,09-May-2019,CE,26900,0.00,0.00,0.00,1448.20,0.00,2843.80,0,0.00,0.00,0,0,-
8,BANKNIFTY,02-May-2019,09-May-2019,CE,27000,2773.00,2874.25,2694.20,2694.20,2694.20,2694.20,9,53.68,5.08,120,120,-
9,BANKNIFTY,02-May-2019,09-May-2019,CE,27100,0.00,0.00,0.00,1303.10,0.00,2644.05,0,0.00,0.00,0,0,-
10,BANKNIFTY,02-May-2019,09-May-2019,CE,27200,2599.90,2599.90,2599.90,2599.90,2599.90,2599.90,1,5.96,0.52,20,20,-
11,BANKNIFTY,02-May-2019,09-May-2019,CE,27300,2499.90,2499.90,2499.90,2499.90,2499.90,2499.90,1,5.96,0.50,20,20,-
12,BANKNIFTY,02-May-2019,09-May-2019,CE,27400,2160.55,2213.25,2160.55,2200.85,2213.20,2200.85,17,100.64,7.48,340,340,-
13,BANKNIFTY,02-May-2019,09-May-2019,CE,27500,2280.00,2410.00,2196.70,2230.70,2240.00,2230.70,148,883.54,69.54,2520,2520,-
14,BANKNIFTY,02-May-2019,09-May-2019,CE,27600,1925.00,2353.00,1925.00,2140.95,2130.00,2140.95,6,35.69,2.57,0,0,-
15,BANKNIFTY,02-May-2019,09-May-2019,CE,27700,0.00,0.00,0.00,917.95,0.00,2045.45,0,0.00,0.00,0,0,-
16,BANKNIFTY,02-May-2019,09-May-2019,CE,27800,1763.95,1763.95,1763.95,1763.95,1763.95,1763.95,8,47.30,2.82,160,160,-
17,BANKNIFTY,02-May-2019,09-May-2019,CE,27900,1724.50,1724.55,1724.50,1724.50,1724.50,1724.50,26,154.05,8.97,520,520,-
18,BANKNIFTY,02-May-2019,09-May-2019,CE,28000,1770.00,1920.00,1671.15,1711.45,1712.75,1711.45,502,2994.25,183.05,9400,9360,-
19,BANKNIFTY,02-May-2019,09-May-2019,CE,28100,0.00,0.00,0.00,704.95,0.00,1648.90,0,0.00,0.00,0,0,-
20,BANKNIFTY,02-May-2019,09-May-2019,CE,28200,1660.00,1660.00,1660.00,1660.00,1660.00,1660.00,1,5.97,0.33,20,20,-
21,BANKNIFTY,02-May-2019,09-May-2019,CE,28300,1560.00,1560.00,1475.00,1475.00,1475.00,1475.00,14,83.44,4.20,280,280,-
22,BANKNIFTY,02-May-2019,09-May-2019,CE,28400,1500.00,1500.00,1300.00,1300.00,1300.00,1300.00,7,41.74,1.98,80,80,-
23,BANKNIFTY,02-May-2019,09-May-2019,CE,28500,1250.00,1423.00,1209.85,1215.20,1220.00,1215.20,64,381.19,16.39,1000,980,-
24,BANKNIFTY,02-May-2019,09-May-2019,CE,28600,0.00,0.00,0.00,488.95,0.00,1166.85,0,0.00,0.00,0,0,-
25,BANKNIFTY,02-May-2019,09-May-2019,CE,28700,983.85,983.85,973.80,978.85,973.80,978.85,2,11.87,0.39,40,40,-
26,BANKNIFTY,02-May-2019,09-May-2019,CE,28800,1040.00,1040.00,842.00,870.35,949.20,870.35,15,89.06,2.66,240,240,-
27,BANKNIFTY,02-May-2019,09-May-2019,CE,28900,952.25,999.65,803.90,817.45,840.50,817.45,23,137.28,4.34,340,340,-
28,BANKNIFTY,02-May-2019,09-May-2019,CE,29000,770.00,960.00,708.85,762.05,760.00,762.05,288,1716.26,45.86,2920,2440,-
29,BANKNIFTY,02-May-2019,09-May-2019,CE,29100,805.00,875.00,644.95,675.00,684.95,675.00,116,691.26,16.14,2120,2120,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26400,0.90,0.90,0.05,0.10,0.10,0.00,8809,46511.90,0.38,83700,-22160,27387.15
265,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26500,0.40,0.65,0.05,0.05,0.05,0.00,34650,183647.01,2.01,407040,-136240,27387.15
266,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26600,0.80,0.80,0.05,0.05,0.05,0.00,38218,203322.85,3.09,154580,-104180,27387.15
267,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26700,1.65,1.65,0.05,0.10,0.05,0.00,76875,410522.03,9.53,304660,-117040,27387.15
268,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26800,3.45,3.45,0.05,0.05,0.05,0.00,219674,1177497.13,44.49,552520,15880,27387.15
269,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,26900,2.70,7.60,0.05,0.10,0.05,0.00,310802,1672223.01,108.25,431240,87960,27387.15
270,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27000,5.00,7.55,0.05,0.10,0.05,0.00,868546,4690608.17,459.77,1126800,254660,27387.15
271,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27100,19.65,19.65,0.05,0.10,0.05,0.00,1014394,5499152.52,1137.04,602820,36960,27387.15
272,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27200,37.60,38.75,0.05,0.15,0.05,0.00,1699649,9249716.21,3625.65,957860,345100,27387.15
273,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27300,63.15,72.90,0.05,0.25,0.05,0.00,2388285,13049136.19,9100.09,1460080,1010760,27387.15
274,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27400,109.80,119.55,0.70,3.00,2.00,0.00,3035791,16651207.69,15073.01,554880,298380,27387.15
275,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27500,158.05,183.00,12.50,52.50,110.00,0.00,1766448,9735566.95,20102.95,38340,-132440,27387.15
276,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27600,215.00,271.00,61.30,146.50,197.00,0.00,353491,1960049.10,8778.78,5340,-26940,27387.15
277,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27700,311.15,365.35,135.15,251.70,300.00,0.00,64642,360887.77,2771.09,1060,-16940,27387.15
278,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27800,398.75,464.35,217.05,366.85,389.00,0.00,13780,77495.58,878.78,5260,-3180,27387.15
279,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,27900,485.20,557.90,309.85,486.05,476.05,0.00,1800,10205.31,161.31,60,-4440,27387.15
280,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28000,601.40,661.20,410.00,573.40,610.00,0.00,4961,28323.67,542.07,120,-15560,27387.15
281,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28100,706.95,742.10,551.35,680.65,690.00,0.00,88,505.84,11.28,20,-420,27387.15
282,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28200,753.75,809.55,618.70,791.20,791.00,0.00,13,75.27,1.95,60,20,27387.15
283,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28300,846.30,914.65,773.05,809.35,773.05,0.00,9,52.45,1.51,60,0,27387.15
284,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28400,0.00,0.00,0.00,1655.80,0.00,0.00,0,0.00,0.00,0,0,27387.15
285,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28500,1080.00,1134.95,944.15,1086.40,1070.05,0.00,370,2185.22,76.22,440,-5740,27387.15
286,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28600,0.00,0.00,0.00,1616.25,0.00,0.00,0,0.00,0.00,0,0,27387.15
287,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28700,0.00,0.00,0.00,1559.85,0.00,0.00,0,0.00,0.00,0,0,27387.15
288,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28800,0.00,0.00,0.00,1635.30,0.00,0.00,0,0.00,0.00,0,0,27387.15
289,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,28900,0.00,0.00,0.00,1603.15,0.00,0.00,0,0.00,0.00,0,0,27387.15
290,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,29000,0.00,0.00,0.00,1552.00,0.00,0.00,0,0.00,0.00,0,0,27387.15
291,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,29100,0.00,0.00,0.00,1525.65,0.00,0.00,0,0.00,0.00,0,0,27387.15
292,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,29200,0.00,0.00,0.00,1429.90,0.00,0.00,0,0.00,0.00,0,0,27387.15
293,BANKNIFTY,07-Feb-2019,07-Feb-2019,PE,24600,0.05,0.65,0.05,0.10,0.10,0.00,792,3896.66,0.02,5240,1980,27387.15

In [79]:
df1= df[df['Option Type'] == 'CE']

In [80]:
df1.shape

(8181, 17)

In [81]:
df=df.drop(["Symbol","Option Type","Settle Price","No. of contracts","Turnover in Lacs","Premium Turnover in Lacs","Open Int","Change in OI","Underlying Value"],axis=1)
df.set_index([pd.DatetimeIndex(df['Expiry']),pd.DatetimeIndex(df['Date']),'Strike Price'],inplace=True)

In [82]:
df.head()

                                           Date       Expiry  Open  High  Low  \
Expiry     Date       Strike Price
2019-05-09 2019-05-02 26200         02-May-2019  09-May-2019   0.0   0.0  0.0
                      32100         02-May-2019  09-May-2019   0.0   0.0  0.0
                      26400         02-May-2019  09-May-2019   0.0   0.0  0.0
                      26500         02-May-2019  09-May-2019   0.0   0.0  0.0
                      26600         02-May-2019  09-May-2019   0.0   0.0  0.0

                                      Close  LTP
Expiry     Date       Strike Price
2019-05-09 2019-05-02 26200         2009.40  0.0
                      32100           83.80  0.0
                      26400         1841.30  0.0
                      26500         1759.45  0.0
                      26600         1679.10  0.0

In [83]:
df_t=pd.DataFrame()
df_b=pd.DataFrame()
df_t['T']=pd.bdate_range('2019-01-01', '2019-01-31',freq='W-THU')
df_b['B']=pd.bdate_range('2019-01-01', '2019-01-31',freq='B')
df_b = df_b.set_index(['B'])
for i in range(4):
    start_date=df_t['T'][i]
    start_date=pd.to_datetime(start_date).date()
    print(start_date)
    end_date=df_t['T'][i+1]
    end_date=pd.to_datetime(start_date).date()
    #print(end_date)

2019-01-03
2019-01-10
2019-01-17
2019-01-24

In [84]:
import os
os.chdir('C:\\Users\\bired\\Desktop\\pics')
df=pd.read_csv('data.csv')
df=df.set_index(['Date'])
df.index = pd.to_datetime(df.index)
round_price=df.loc[start_date]['Close']
x=np.round(round_price,decimals=-2)
print(x)

27300.0

In [85]:
close_list = [x]
addsub = [-400,-300,-200,-100,0,100,200,300,400]
a=[[i+j for j in addsub]for i in close_list]
print(a)

[[26900.0, 27000.0, 27100.0, 27200.0, 27300.0, 27400.0, 27500.0, 27600.0, 27700.0]]

In [86]:
start_date1=start_date+pd.offsets.BDay(1)
start_date1=pd.datetime.date(start_date1)

start_date2=start_date+pd.offsets.BDay(2)
start_date2=pd.datetime.date(start_date2)

start_date3=start_date+pd.offsets.BDay(3)
start_date3=pd.datetime.date(start_date3)

start_date4=start_date+pd.offsets.BDay(4)
start_date4=pd.datetime.date(start_date4)

start_date5=start_date+pd.offsets.BDay(5)
start_date5=pd.datetime.date(start_date5)

In [87]:
n3=df.loc[end_date].loc[start_date].loc[a[0][0]:a[0][-1]]['Close']
n4=df.loc[end_date].loc[start_date1].loc[a[0][0]:a[0][-1]]['Close']
n7=df.loc[end_date].loc[start_date2].loc[a[0][0]:a[0][-1]]['Close']
n8=df.loc[end_date].loc[start_date3].loc[a[0][0]:a[0][-1]]['Close']
n9=df.loc[end_date].loc[start_date4].loc[a[0][0]:a[0][-1]]['Close']
n10=df.loc[end_date].loc[start_date5].loc[a[0][0]:a[0][-1]]['Close']

KeyError: datetime.date(2019, 1, 24)

In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [81]:
df_t=pd.DataFrame()
df_b=pd.DataFrame()
df_t['T']=pd.bdate_range('2019-01-01', '2019-01-31',freq='W-THU')
df_b['B']=pd.bdate_range('2019-01-01', '2019-01-31',freq='B')
df_b = df_b.set_index(['B'])
start_date=df_t['T'][0]
start_date=pd.to_datetime(start_date).date()
end_date=df_t['T'][1]
end_date=pd.to_datetime(end_date).date()

In [82]:
import os
os.chdir('C:\\Users\\bired\\Desktop\\pics')
df=pd.read_csv('data.csv')
df=df.set_index(['Date'])
df.index = pd.to_datetime(df.index)
round_price=df.loc[start_date]['Close']
x=np.round(round_price,decimals=-2)
print(x)

27000.0

In [83]:
close_list = [x]
addsub = [-400,-300,-200,-100,0,100,200,300,400]
a=[[i+j for j in addsub]for i in close_list]
print(a)

[[26600.0, 26700.0, 26800.0, 26900.0, 27000.0, 27100.0, 27200.0, 27300.0, 27400.0]]

In [95]:
os.chdir('C:\\Users\\bired\\Desktop\\pics')
df=pd.read_csv('nifty3jan.csv')

In [96]:
df=df.drop(["Symbol","Option Type","Settle Price","No. of contracts","Turnover in Lacs","Premium Turnover in Lacs","Open Int","Change in OI","Underlying Value"],axis=1)
df.set_index([pd.DatetimeIndex(df['Expiry']),pd.DatetimeIndex(df['Date']),'Strike Price'],inplace=True)

In [97]:
df.head()

                                           Date       Expiry  Open  High  Low  \
Expiry     Date       Strike Price
2019-01-10 2019-01-03 23900         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      29000         03-Jan-2019  10-Jan-2019   2.9   2.9  1.1
                      24100         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      24200         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      24300         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0

                                      Close      LTP
Expiry     Date       Strike Price
2019-01-10 2019-01-03 23900         3287.95  3287.95
                      29000            1.20     1.10
                      24100         2124.80     0.00
                      24200         2051.50     0.00
                      24300         1978.35     0.00

In [98]:
start_date1=start_date+pd.offsets.BDay(1)
start_date1=pd.datetime.date(start_date1)

start_date2=start_date+pd.offsets.BDay(2)
start_date2=pd.datetime.date(start_date2)

start_date3=start_date+pd.offsets.BDay(3)
start_date3=pd.datetime.date(start_date3)

start_date4=start_date+pd.offsets.BDay(4)
start_date4=pd.datetime.date(start_date4)

start_date5=start_date+pd.offsets.BDay(5)
start_date5=pd.datetime.date(start_date5)

In [99]:
n3=df.loc[end_date].loc[start_date].loc[a[0][0]:a[0][-1]]['Close']
n4=df.loc[end_date].loc[start_date1].loc[a[0][0]:a[0][-1]]['Close']
n7=df.loc[end_date].loc[start_date2].loc[a[0][0]:a[0][-1]]['Close']
n8=df.loc[end_date].loc[start_date3].loc[a[0][0]:a[0][-1]]['Close']
n9=df.loc[end_date].loc[start_date4].loc[a[0][0]:a[0][-1]]['Close']
n10=df.loc[end_date].loc[start_date5].loc[a[0][0]:a[0][-1]]['Close']

In [100]:
n10

Strike Price
26600    918.45
26700    831.95
26800    725.15
26900    630.55
27000    521.35
27100    413.35
27200    318.70
27300    222.40
27400    124.15
Name: Close, dtype: float64

In [101]:
from functools import reduce
dfs = [n3,n4,n7,n8,n9,n10]
df = reduce(lambda a,b: pd.merge(a,b,on='Strike Price'), dfs)
df.columns = [start_date,start_date1,start_date2,start_date3,start_date4,start_date5]
df

,2019-01-03,2019-01-04,2019-01-07,2019-01-08,2019-01-09,2019-01-10
Strike Price,,,,,,
26600,476.20,665.05,696.20,872.90,1044.45,918.45
26700,403.70,566.85,594.60,776.00,935.85,831.95
26800,338.35,491.95,507.05,677.60,845.25,725.15
26900,282.45,414.95,421.00,590.80,747.25,630.55
27000,231.65,342.30,344.15,501.15,650.75,521.35
27100,187.30,280.00,275.75,404.45,553.55,413.35
27200,148.20,221.75,214.40,317.95,458.05,318.70
27300,114.50,171.70,161.95,244.45,360.75,222.40
27400,86.75,128.25,119.50,181.60,275.05,124.15

# consider 2nd week as df2

In [159]:
import os
os.chdir("C:\\Users\\bired\\Desktop\\pics")
df2=pd.read_csv("nifty.ce.csv")

In [160]:
df2.head()

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value
0,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,23900,0.0,0.0,0.0,3287.95,3287.95,3092.05,0,0.00,0.00,0,0,26959.85
1,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,29000,2.9,2.9,1.1,1.20,1.10,1.20,555,3219.15,0.15,7680,7300,26959.85
2,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24100,0.0,0.0,0.0,2124.80,0.00,2892.35,0,0.00,0.00,0,0,26959.85
3,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24200,0.0,0.0,0.0,2051.50,0.00,2792.50,0,0.00,0.00,0,0,26959.85
4,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24300,0.0,0.0,0.0,1978.35,0.00,2692.60,0,0.00,0.00,0,0,26959.85

In [162]:
df2.iloc[2:]

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value
2,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24100,0.00,0.00,0.00,2124.80,0.00,2892.35,0,0.00,0.00,0,0,26959.85
3,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24200,0.00,0.00,0.00,2051.50,0.00,2792.50,0,0.00,0.00,0,0,26959.85
4,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24300,0.00,0.00,0.00,1978.35,0.00,2692.60,0,0.00,0.00,0,0,26959.85
5,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24400,0.00,0.00,0.00,1906.65,0.00,2592.75,0,0.00,0.00,0,0,26959.85
6,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24500,2627.00,2634.45,2480.00,2480.00,2480.00,2480.00,77,415.84,38.54,1520,1480,26959.85
7,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24600,0.00,0.00,0.00,1766.65,0.00,2393.00,0,0.00,0.00,0,0,26959.85
8,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24700,0.00,0.00,0.00,1699.35,0.00,2293.15,0,0.00,0.00,0,0,26959.85
9,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24800,0.00,0.00,0.00,1633.55,0.00,2193.30,0,0.00,0.00,0,0,26959.85
10,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24900,2050.00,2050.00,2050.00,2050.00,2050.00,2050.00,1,5.39,0.41,20,20,26959.85
11,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25000,2150.00,2150.00,1963.30,1989.25,1977.30,1989.25,201,1085.94,80.94,3440,3440,26959.85
12,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25100,0.00,0.00,0.00,1445.20,0.00,1893.90,0,0.00,0.00,0,0,26959.85
13,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25200,0.00,0.00,0.00,1385.50,0.00,1794.20,0,0.00,0.00,0,0,26959.85
14,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25300,0.00,0.00,0.00,1327.35,0.00,1694.60,0,0.00,0.00,0,0,26959.85
15,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25400,0.00,0.00,0.00,1270.75,0.00,1595.20,0,0.00,0.00,0,0,26959.85
16,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25500,1660.05,1675.00,1550.00,1555.00,1555.00,1555.00,9,48.82,2.92,220,160,26959.85
17,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25600,1310.00,1310.00,1310.00,1310.00,1310.00,1310.00,1,5.38,0.26,20,20,26959.85
18,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25700,1338.50,1338.50,1300.00,1300.00,1300.00,1300.00,12,64.88,3.20,240,240,26959.85
19,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25800,1230.00,1230.00,1230.00,1230.00,1230.00,1230.00,2,10.81,0.49,40,40,26959.85
20,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25900,1248.00,1248.00,1079.10,1093.00,1093.00,1093.00,6,32.46,1.38,100,100,26959.85
21,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26000,1140.00,1200.00,970.20,995.95,980.10,995.95,3810,20611.42,799.42,71280,70940,26959.85
22,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26100,0.00,0.00,0.00,918.40,0.00,918.05,0,0.00,0.00,0,0,26959.85
23,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26200,935.85,1008.00,794.55,813.45,812.50,813.45,826,4472.28,144.04,15220,15200,26959.85
24,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26300,845.35,910.10,706.00,719.10,717.95,719.10,771,4180.58,125.12,13400,13340,26959.85
25,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26400,757.60,825.75,613.45,630.30,614.25,630.30,1597,8661.90,229.74,48960,19500,26959.85
26,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26500,737.45,739.00,533.50,552.75,541.90,552.75,3164,17150.33,381.13,66100,34300,26959.85
27,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26600,593.35,650.00,465.00,476.20,472.00,476.20,637,3454.39,65.55,10300,9920,26959.85
28,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26700,518.00,555.00,389.50,403.70,389.95,403.70,2630,14295.08,250.88,33360,32920,26959.85
29,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26800,475.00,495.00,328.10,338.35,336.00,338.35,1867,10139.13,132.01,19500,18040,26959.85
30,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26900,420.00,421.85,265.80,282.45,268.95,282.45,6293,34235.56,379.22,31100,30360,26959.85
31,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,27000,356.60,375.95,217.95,231.65,226.00,231.65,63747,347587.96,3354.16,303240,266200,26959.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26400,1204.45,1219.15,1077.45,1128.20,1112.60,0.00,3708,20415.73,837.49,0,-47880,27528.55
287,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26500,1113.00,1120.00,975.55,1020.40,1014.00,0.00,3183,17534.81,664.91,1340,-37480,27528.55
288,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26600,1005.30,1007.30,882.85,918.45,914.00,0.00,897,4941.53,169.49,180,-10660,27528.55
289,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26700,875.55,911.05,780.00,831.95,809.00,0.00,1481,8158.16,249.62,60,-13600,27528.55
290,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26800,801.25,820.25,684.50,725.15,710.00,0.00,1650,9086.54,242.54,180,-18800,27528.55
291,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26900,690.70,714.00,567.95,630.55,626.90,0.00,1254,6907.08,160.56,280,-11920,27528.55
292,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27000,600.00,622.35,469.25,521.35,525.05,0.00,12496,68861.60,1383.20,2180,-78680,27528.55
293,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27100,487.60,522.40,370.05,413.35,396.90,0.00,4744,26129.97,417.49,2860,-23080,27528.55
294,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27200,405.90,438.10,273.00,318.70,311.00,0.00,9624,53017.43,662.87,1240,-34960,27528.55
295,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27300,320.25,348.70,174.00,222.40,224.90,0.00,46241,254724.82,2248.96,2420,-86540,27528.55
296,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27400,260.00,260.00,78.60,124.15,108.00,0.00,271635,1496320.60,7760.80,5600,-147600,27528.55
297,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27500,149.95,184.25,6.65,22.85,7.50,0.00,1917794,10567968.89,20101.89,170760,-149320,27528.55
298,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27600,100.10,109.30,0.05,1.35,0.05,0.00,3414164,18863173.00,16987.72,2046400,1678600,27528.55
299,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27700,66.60,66.60,0.05,0.15,0.05,0.00,3065990,16993727.15,8142.55,2358300,1755780,27528.55
300,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27800,21.05,30.95,0.05,0.10,0.05,0.00,2125285,11819025.90,2441.30,2023880,1273780,27528.55
301,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27900,17.45,17.45,0.05,0.05,0.05,0.00,1460254,8148782.85,565.53,1383840,256360,27528.55
302,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28000,5.80,5.80,0.05,0.05,0.05,0.00,1311697,7345698.24,195.04,1481080,390760,27528.55
303,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28100,1.10,1.90,0.05,0.05,0.05,0.00,464508,2610561.24,26.28,390880,80480,27528.55
304,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28200,0.35,0.55,0.05,0.05,0.05,0.00,60843,343156.01,1.49,217180,-15260,27528.55
305,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28300,0.20,0.40,0.05,0.05,0.05,0.00,26417,149520.77,0.55,266440,-44380,27528.55
306,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28400,0.10,0.40,0.05,0.05,0.05,0.00,8919,50660.05,0.13,78660,4140,27528.55
307,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28500,0.10,0.20,0.05,0.05,0.05,0.00,8536,48655.32,0.12,114160,-6940,27528.55
308,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28600,0.05,0.10,0.05,0.05,0.05,0.00,205,1172.60,0.00,6740,1360,27528.55
309,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28700,0.15,0.15,0.05,0.05,0.05,0.00,152,872.48,0.00,6340,1980,27528.55
310,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28800,0.00,0.00,0.00,0.15,0.15,0.00,0,0.00,0.00,2640,0,27528.55
311,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28900,0.05,0.05,0.05,0.05,0.05,0.00,55,317.90,0.00,7940,0,27528.55
312,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29000,0.05,0.05,0.05,0.05,0.05,0.00,489,2836.20,0.00,11760,1160,27528.55
313,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29100,0.00,0.00,0.00,0.05,0.00,0.00,0,0.00,0.00,0,0,27528.55
314,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29200,0.00,0.00,0.00,0.05,0.00,0.00,0,0.00,0.00,0,0,27528.55
315,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,24000,0.00,0.00,0.00,3390.75,3390.75,0.00,0,0.00,0.00,0,0,27528.55

In [156]:
df2.shape

(314, 7)

In [163]:
df2.iloc[2:]

,Symbol,Date,Expiry,Option Type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover in Lacs,Premium Turnover in Lacs,Open Int,Change in OI,Underlying Value
2,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24100,0.00,0.00,0.00,2124.80,0.00,2892.35,0,0.00,0.00,0,0,26959.85
3,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24200,0.00,0.00,0.00,2051.50,0.00,2792.50,0,0.00,0.00,0,0,26959.85
4,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24300,0.00,0.00,0.00,1978.35,0.00,2692.60,0,0.00,0.00,0,0,26959.85
5,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24400,0.00,0.00,0.00,1906.65,0.00,2592.75,0,0.00,0.00,0,0,26959.85
6,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24500,2627.00,2634.45,2480.00,2480.00,2480.00,2480.00,77,415.84,38.54,1520,1480,26959.85
7,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24600,0.00,0.00,0.00,1766.65,0.00,2393.00,0,0.00,0.00,0,0,26959.85
8,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24700,0.00,0.00,0.00,1699.35,0.00,2293.15,0,0.00,0.00,0,0,26959.85
9,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24800,0.00,0.00,0.00,1633.55,0.00,2193.30,0,0.00,0.00,0,0,26959.85
10,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,24900,2050.00,2050.00,2050.00,2050.00,2050.00,2050.00,1,5.39,0.41,20,20,26959.85
11,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25000,2150.00,2150.00,1963.30,1989.25,1977.30,1989.25,201,1085.94,80.94,3440,3440,26959.85
12,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25100,0.00,0.00,0.00,1445.20,0.00,1893.90,0,0.00,0.00,0,0,26959.85
13,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25200,0.00,0.00,0.00,1385.50,0.00,1794.20,0,0.00,0.00,0,0,26959.85
14,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25300,0.00,0.00,0.00,1327.35,0.00,1694.60,0,0.00,0.00,0,0,26959.85
15,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25400,0.00,0.00,0.00,1270.75,0.00,1595.20,0,0.00,0.00,0,0,26959.85
16,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25500,1660.05,1675.00,1550.00,1555.00,1555.00,1555.00,9,48.82,2.92,220,160,26959.85
17,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25600,1310.00,1310.00,1310.00,1310.00,1310.00,1310.00,1,5.38,0.26,20,20,26959.85
18,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25700,1338.50,1338.50,1300.00,1300.00,1300.00,1300.00,12,64.88,3.20,240,240,26959.85
19,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25800,1230.00,1230.00,1230.00,1230.00,1230.00,1230.00,2,10.81,0.49,40,40,26959.85
20,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,25900,1248.00,1248.00,1079.10,1093.00,1093.00,1093.00,6,32.46,1.38,100,100,26959.85
21,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26000,1140.00,1200.00,970.20,995.95,980.10,995.95,3810,20611.42,799.42,71280,70940,26959.85
22,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26100,0.00,0.00,0.00,918.40,0.00,918.05,0,0.00,0.00,0,0,26959.85
23,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26200,935.85,1008.00,794.55,813.45,812.50,813.45,826,4472.28,144.04,15220,15200,26959.85
24,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26300,845.35,910.10,706.00,719.10,717.95,719.10,771,4180.58,125.12,13400,13340,26959.85
25,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26400,757.60,825.75,613.45,630.30,614.25,630.30,1597,8661.90,229.74,48960,19500,26959.85
26,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26500,737.45,739.00,533.50,552.75,541.90,552.75,3164,17150.33,381.13,66100,34300,26959.85
27,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26600,593.35,650.00,465.00,476.20,472.00,476.20,637,3454.39,65.55,10300,9920,26959.85
28,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26700,518.00,555.00,389.50,403.70,389.95,403.70,2630,14295.08,250.88,33360,32920,26959.85
29,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26800,475.00,495.00,328.10,338.35,336.00,338.35,1867,10139.13,132.01,19500,18040,26959.85
30,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,26900,420.00,421.85,265.80,282.45,268.95,282.45,6293,34235.56,379.22,31100,30360,26959.85
31,BANKNIFTY,03-Jan-2019,10-Jan-2019,CE,27000,356.60,375.95,217.95,231.65,226.00,231.65,63747,347587.96,3354.16,303240,266200,26959.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26400,1204.45,1219.15,1077.45,1128.20,1112.60,0.00,3708,20415.73,837.49,0,-47880,27528.55
287,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26500,1113.00,1120.00,975.55,1020.40,1014.00,0.00,3183,17534.81,664.91,1340,-37480,27528.55
288,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26600,1005.30,1007.30,882.85,918.45,914.00,0.00,897,4941.53,169.49,180,-10660,27528.55
289,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26700,875.55,911.05,780.00,831.95,809.00,0.00,1481,8158.16,249.62,60,-13600,27528.55
290,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26800,801.25,820.25,684.50,725.15,710.00,0.00,1650,9086.54,242.54,180,-18800,27528.55
291,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,26900,690.70,714.00,567.95,630.55,626.90,0.00,1254,6907.08,160.56,280,-11920,27528.55
292,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27000,600.00,622.35,469.25,521.35,525.05,0.00,12496,68861.60,1383.20,2180,-78680,27528.55
293,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27100,487.60,522.40,370.05,413.35,396.90,0.00,4744,26129.97,417.49,2860,-23080,27528.55
294,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27200,405.90,438.10,273.00,318.70,311.00,0.00,9624,53017.43,662.87,1240,-34960,27528.55
295,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27300,320.25,348.70,174.00,222.40,224.90,0.00,46241,254724.82,2248.96,2420,-86540,27528.55
296,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27400,260.00,260.00,78.60,124.15,108.00,0.00,271635,1496320.60,7760.80,5600,-147600,27528.55
297,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27500,149.95,184.25,6.65,22.85,7.50,0.00,1917794,10567968.89,20101.89,170760,-149320,27528.55
298,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27600,100.10,109.30,0.05,1.35,0.05,0.00,3414164,18863173.00,16987.72,2046400,1678600,27528.55
299,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27700,66.60,66.60,0.05,0.15,0.05,0.00,3065990,16993727.15,8142.55,2358300,1755780,27528.55
300,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27800,21.05,30.95,0.05,0.10,0.05,0.00,2125285,11819025.90,2441.30,2023880,1273780,27528.55
301,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,27900,17.45,17.45,0.05,0.05,0.05,0.00,1460254,8148782.85,565.53,1383840,256360,27528.55
302,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28000,5.80,5.80,0.05,0.05,0.05,0.00,1311697,7345698.24,195.04,1481080,390760,27528.55
303,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28100,1.10,1.90,0.05,0.05,0.05,0.00,464508,2610561.24,26.28,390880,80480,27528.55
304,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28200,0.35,0.55,0.05,0.05,0.05,0.00,60843,343156.01,1.49,217180,-15260,27528.55
305,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28300,0.20,0.40,0.05,0.05,0.05,0.00,26417,149520.77,0.55,266440,-44380,27528.55
306,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28400,0.10,0.40,0.05,0.05,0.05,0.00,8919,50660.05,0.13,78660,4140,27528.55
307,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28500,0.10,0.20,0.05,0.05,0.05,0.00,8536,48655.32,0.12,114160,-6940,27528.55
308,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28600,0.05,0.10,0.05,0.05,0.05,0.00,205,1172.60,0.00,6740,1360,27528.55
309,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28700,0.15,0.15,0.05,0.05,0.05,0.00,152,872.48,0.00,6340,1980,27528.55
310,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28800,0.00,0.00,0.00,0.15,0.15,0.00,0,0.00,0.00,2640,0,27528.55
311,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,28900,0.05,0.05,0.05,0.05,0.05,0.00,55,317.90,0.00,7940,0,27528.55
312,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29000,0.05,0.05,0.05,0.05,0.05,0.00,489,2836.20,0.00,11760,1160,27528.55
313,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29100,0.00,0.00,0.00,0.05,0.00,0.00,0,0.00,0.00,0,0,27528.55
314,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,29200,0.00,0.00,0.00,0.05,0.00,0.00,0,0.00,0.00,0,0,27528.55
315,BANKNIFTY,10-Jan-2019,10-Jan-2019,CE,24000,0.00,0.00,0.00,3390.75,3390.75,0.00,0,0.00,0.00,0,0,27528.55

In [164]:
df2=df2.drop(["Symbol","Option Type","Settle Price","No. of contracts","Turnover in Lacs","Premium Turnover in Lacs","Open Int","Change in OI","Underlying Value"],axis=1)
df2.set_index([pd.DatetimeIndex(df2['Expiry']),pd.DatetimeIndex(df2['Date']),'Strike Price'],inplace=True)

In [165]:
df2.head()

                                           Date       Expiry  Open  High  Low  \
Expiry     Date       Strike Price
2019-01-10 2019-01-03 23900         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      29000         03-Jan-2019  10-Jan-2019   2.9   2.9  1.1
                      24100         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      24200         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0
                      24300         03-Jan-2019  10-Jan-2019   0.0   0.0  0.0

                                      Close      LTP
Expiry     Date       Strike Price
2019-01-10 2019-01-03 23900         3287.95  3287.95
                      29000            1.20     1.10
                      24100         2124.80     0.00
                      24200         2051.50     0.00
                      24300         1978.35     0.00

In [170]:
df.shape

(7, 6)

In [171]:
df1.shape

(117, 6)

In [167]:
df_all = pd.concat([df1, df2])
df_all

C:\Users\bired\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,Close,Date,Expiry,High,LTP,Low,Open,Shares Traded,Turnover (Rs. Cr)
01-Jan-2019,27392.40,NaN,NaN,27430.55,NaN,27019.05,27231.40,116379065.0,3497.39
02-Jan-2019,27174.70,NaN,NaN,27397.55,NaN,27077.60,27297.00,176599164.0,4422.44
03-Jan-2019,26959.85,NaN,NaN,27206.20,NaN,26923.75,27181.60,151201387.0,4032.83
04-Jan-2019,27195.00,NaN,NaN,27274.50,NaN,26926.10,26999.70,189451222.0,4440.79
07-Jan-2019,27304.55,NaN,NaN,27477.80,NaN,27279.55,27378.65,161026470.0,4112.84
08-Jan-2019,27509.50,NaN,NaN,27542.40,NaN,27161.95,27301.90,150550286.0,4359.43
09-Jan-2019,27720.40,NaN,NaN,27754.45,NaN,27409.50,27651.25,199818392.0,6148.74
10-Jan-2019,27528.55,NaN,NaN,27713.55,NaN,27488.20,27713.55,139266179.0,4308.94
11-Jan-2019,27453.90,NaN,NaN,27612.45,NaN,27382.45,27602.80,116552104.0,3510.63
14-Jan-2019,27248.25,NaN,NaN,27389.80,NaN,27182.20,27389.20,212863498.0,4859.32
15-Jan-2019,27400.75,NaN,NaN,27447.55,NaN,27317.10,27317.55,161396521.0,3884.40
16-Jan-2019,27483.70,NaN,NaN,27554.75,NaN,27403.05,27405.65,183688179.0,4155.93
17-Jan-2019,27528.75,NaN,NaN,27611.55,NaN,27335.15,27568.60,212321274.0,4941.09
18-Jan-2019,27456.70,NaN,NaN,27576.45,NaN,27410.65,27550.05,129067258.0,3343.81
21-Jan-2019,27533.60,NaN,NaN,27622.20,NaN,27388.50,27514.55,128881764.0,4626.77
22-Jan-2019,27482.25,NaN,NaN,27533.35,NaN,27385.40,27526.55,138997867.0,4661.51
23-Jan-2019,27250.75,NaN,NaN,27564.70,NaN,27189.60,27493.10,126935738.0,3525.23
24-Jan-2019,27266.40,NaN,NaN,27342.35,NaN,27142.80,27273.50,210279603.0,5373.42
25-Jan-2019,27115.30,NaN,NaN,27433.55,NaN,27045.20,27261.45,284535180.0,7269.49
28-Jan-2019,26653.05,NaN,NaN,27134.20,NaN,26587.95,27041.45,181836992.0,5404.63
29-Jan-2019,26573.40,NaN,NaN,26743.85,NaN,26441.55,26616.25,194369347.0,5235.15
30-Jan-2019,26825.50,NaN,NaN,26916.25,NaN,26693.70,26789.75,249270714.0,8955.81
31-Jan-2019,27295.45,NaN,NaN,27325.05,NaN,26891.05,26969.15,306292995.0,9985.48
01-Feb-2019,27085.95,NaN,NaN,27533.05,NaN,26930.45,27334.55,238794913.0,6813.15
04-Feb-2019,27186.60,NaN,NaN,27243.80,NaN,26825.55,26974.00,173078574.0,4342.07
05-Feb-2019,27271.70,NaN,NaN,27348.25,NaN,27153.20,27226.05,189860429.0,4160.27
06-Feb-2019,27402.35,NaN,NaN,27428.65,NaN,27294.10,27326.20,164747849.0,3816.51
07-Feb-2019,27387.15,NaN,NaN,27589.75,NaN,27322.95,27424.10,156626117.0,3637.06
08-Feb-2019,27294.40,NaN,NaN,27482.10,NaN,27221.25,27302.65,142258447.0,3838.29
11-Feb-2019,27227.80,NaN,NaN,27305.90,NaN,27151.55,27240.50,117311228.0,3186.38
...,...,...,...,...,...,...,...,...,...
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26400)",1128.20,10-Jan-2019,10-Jan-2019,1219.15,1112.60,1077.45,1204.45,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26500)",1020.40,10-Jan-2019,10-Jan-2019,1120.00,1014.00,975.55,1113.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26600)",918.45,10-Jan-2019,10-Jan-2019,1007.30,914.00,882.85,1005.30,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26700)",831.95,10-Jan-2019,10-Jan-2019,911.05,809.00,780.00,875.55,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26800)",725.15,10-Jan-2019,10-Jan-2019,820.25,710.00,684.50,801.25,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 26900)",630.55,10-Jan-2019,10-Jan-2019,714.00,626.90,567.95,690.70,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27000)",521.35,10-Jan-2019,10-Jan-2019,622.35,525.05,469.25,600.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27100)",413.35,10-Jan-2019,10-Jan-2019,522.40,396.90,370.05,487.60,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27200)",318.70,10-Jan-2019,10-Jan-2019,438.10,311.00,273.00,405.90,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27300)",222.40,10-Jan-2019,10-Jan-2019,348.70,224.90,174.00,320.25,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27400)",124.15,10-Jan-2019,10-Jan-2019,260.00,108.00,78.60,260.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27500)",22.85,10-Jan-2019,10-Jan-2019,184.25,7.50,6.65,149.95,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27600)",1.35,10-Jan-2019,10-Jan-2019,109.30,0.05,0.05,100.10,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27700)",0.15,10-Jan-2019,10-Jan-2019,66.60,0.05,0.05,66.60,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27800)",0.10,10-Jan-2019,10-Jan-2019,30.95,0.05,0.05,21.05,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 27900)",0.05,10-Jan-2019,10-Jan-2019,17.45,0.05,0.05,17.45,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28000)",0.05,10-Jan-2019,10-Jan-2019,5.80,0.05,0.05,5.80,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28100)",0.05,10-Jan-2019,10-Jan-2019,1.90,0.05,0.05,1.10,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28200)",0.05,10-Jan-2019,10-Jan-2019,0.55,0.05,0.05,0.35,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28300)",0.05,10-Jan-2019,10-Jan-2019,0.40,0.05,0.05,0.20,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28400)",0.05,10-Jan-2019,10-Jan-2019,0.40,0.05,0.05,0.10,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28500)",0.05,10-Jan-2019,10-Jan-2019,0.20,0.05,0.05,0.10,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28600)",0.05,10-Jan-2019,10-Jan-2019,0.10,0.05,0.05,0.05,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28700)",0.05,10-Jan-2019,10-Jan-2019,0.15,0.05,0.05,0.15,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28800)",0.15,10-Jan-2019,10-Jan-2019,0.00,0.15,0.00,0.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 28900)",0.05,10-Jan-2019,10-Jan-2019,0.05,0.05,0.05,0.05,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 29000)",0.05,10-Jan-2019,10-Jan-2019,0.05,0.05,0.05,0.05,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 29100)",0.05,10-Jan-2019,10-Jan-2019,0.00,0.00,0.00,0.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 29200)",0.05,10-Jan-2019,10-Jan-2019,0.00,0.00,0.00,0.00,NaN,NaN
"(2019-01-10 00:00:00, 2019-01-10 00:00:00, 24000)",3390.75,10-Jan-2019,10-Jan-2019,0.00,3390.75,0.00,0.00,NaN,NaN